---
# E: This handles the loading of my automations
# F: Permer de charger mes automations
#
# https://www.home-assistant.io/docs/automation/
#
automation: !include ../automations.yaml
automation split: !include_dir_merge_list ../automations
