---
# E: Configures the official Home Assistant frontend.
# F: Configuration the l'interface de Home Assistant.
#
# https://www.home-assistant.io/components/frontend/
#

# Enable config panel in UI
frontend:
  # We can define additional/custom themes for the frontend here.
  themes: !include_dir_merge_named ../themes
