---
# Logger to help debug
#
# https://www.home-assistant.io/components/logger/
#
logger:
  default: warning
#  logs:
#    custom_components.pool_pump: debug
#    homeassistant.components.meteo_france: debug
#    custom_components.renaultze: debug
#    homeassistant.components.vacuum.xiaomi_miio: debug
