---
# E: The zeroconf integration will scan the network for
# supported devices and services.
# F: L'integration zeroconf scan le réseau pour découvrir
# les appareils et les services compatibles
#
# E: It allows to make Home Assistant server discoverable.
# F: Il permet aussi de renfre le serveur Home Assistant
# automatiquement visible sur le réseau.
#
# https://www.home-assistant.io/integrations/zeroconf/
#
zeroconf: ~
