---
# Launch my Xiaomi Vacuum in the office
#
# https://www.home-assistant.io/components/vacuum/
# https://www.home-assistant.io/components/vacuum.xiaomi_miio/
#
alias: Lance Rocky dans la chambre d'Athénaïs
sequence:
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.rocky
      fan_speed: Standard

  - service: xiaomi_miio.vacuum_clean_zone
    data:
      entity_id: vacuum.rocky
      repeats: "{{ repetition | default(1) }}"
      zone:
        - [19200, 32500, 22000, 35500]
  - service: logbook.log
    data:
      name: Rocky
      message: starts cleaning kids bathroom
      entity_id: vacuum.rocky
      domain: vacuum

  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.vacuum_need_to_be_emptied
