---
# Launch my Xiaomi Vacuum on the carpet
#
# https://www.home-assistant.io/components/vacuum/
# https://www.home-assistant.io/components/vacuum.xiaomi_miio/
#
alias: Lance Rocky sur le tapis
sequence:
  # Set fan speed at maximum power
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.rocky
      fan_speed: max
  # Clean the carpet 3 times.
  - service: xiaomi_miio.vacuum_clean_zone
    data:
      entity_id: vacuum.rocky
      repeats: 3
      zone:
        - [28000, 25900, 29700, 28900]
  - service: logbook.log
    data:
      name: Rocky
      message: starts cleaning the carpet
      entity_id: vacuum.rocky
      domain: vacuum

  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.vacuum_need_to_be_emptied
