---
# Launch my Xiaomi Vacuum in the office
#
# https://www.home-assistant.io/components/vacuum/
# https://www.home-assistant.io/components/vacuum.xiaomi_miio/
#
alias: Lance Rocky dans le bureau
sequence:
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.rocky
      fan_speed: Standard
  - service: xiaomi_miio.vacuum_clean_zone
    data:
      entity_id: vacuum.rocky
      repeats: "{{ repetition | default(1) }}"
      zone:
        - [24050, 34950, 25150, 35750]
        - [21300, 35750, 25150, 38650]
  - service: logbook.log
    data:
      name: Rocky
      message: starts cleaning the office
      entity_id: vacuum.rocky
      domain: vacuum

  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.vacuum_need_to_be_emptied
