---
# Automation for HA weekly backup.
#
# Use bash script to create the snapshot, synchronize with NAS by rsync
# and clean local old backup.
#

# Generate the HA config archive weekly
- alias: Weekly Backup Monday at 3 AM
  initial_state: 'on'
  trigger:
    platform: time
    at: '3:00:00'
  condition:
    - condition: time
      weekday:
        - mon
  action:
    - service: hassio.addon_stdin
      data:
        addon: a0d7b954_ssh
        input: "/config/scripts/shell/hassio_backup.sh"
    - service: notify.telegram
      data:
        message: Creation du backup hebomadaire.
