---
# FR: Allume les lumières de Noël pour une plage spécifique
# EN: Switch on the Xmas light on a specific time range
#
# https://www.home-assistant.io/integrations/tod/
#
- id: '1608133504042'
  alias: Allumer les lumières de Noël
  description: Allume les lumière de Noël sur une plage horraire
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.plage_horaire_pour_lumieres_de_noel
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.plage_horaire_pour_lumieres_de_noel
              state: 'on'
              sequence:
                - service: homeassistant.turn_on
                  data: {}
                  entity_id: switch.noel
