---
# FR: Allume les lumières de Noël pour une plage spécifique
# EN: Switch on the Xmas light on a specific time range
#
# https://www.home-assistant.io/integrations/tod/
#
- id: '1608133504042'
  alias: Allumer les lumières de Noël
  description: Allume les lumière de Noël sur une plage horraire
  use_blueprint:
    path: my_blueprints/turn_on_with_bool_state.yaml
    input:
      binary_sensor: binary_sensor.plage_horaire_pour_lumieres_de_noel
      target_entity:
        entity_id: switch.noel
