---
# FR: Envoie une notificatin quand la pluie est attendue dans la prochaine heure
# EN: Sent a notification if rain is expected in the hour
#
# FR: - Envoie une notification sur Telegram pour chaque changement d'heure estimée.
#     - Envoie une notificatino sur la Google Home si la pluie est attendue dans moins de 5 minutes.
#     - Une fois qu'il pleue, évite de répéter les notifications jusqu'à plus de pluie attendue
#       dans la prochaine heure.
#
# EN: - Send a notification on Telegram each time rain estimatin time change.
#     - Send a notification on Google Home if rain is expected in less than 5 minutes.
#     - When it's raining, avoid to send notification unitil nom more rain is expected in the
#       following hour.
#
# https://www.home-assistant.io/docs/automation/trigger/#template-trigger
# https://www.home-assistant.io/docs/scripts/conditions/#template-condition
#
- description: Envoie une notification quand la pluie est attendue dans l'heure
  alias: send_notification_when_rain_is_expected
  id: 30f4e5a8-df44-11ea-87d0-0242ac130003
  trigger:
    platform: state
    entity_id: sensor.home_next_rain
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
    - condition: template
      value_template: "{% if is_state('sensor.home_next_rain', 'unknown') %}false{% else %}true{% endif %}"
    - condition: state
      entity_id: input_boolean.stop_rain_notification
      state: 'off'
  action:
    - service: notify.telegram
      data:
        message: "La pluie est attendue à {{ as_timestamp(states('sensor.home_next_rain')) | timestamp_custom('%H:%M', True) }}."

- description: Envoie une notification quand plus de pluie prévue dans la prochaine heure
  alias: send_notification_when_no_more_rain_is_expected"
  id: 451a1620-dfdf-11ea-89f8-315bf8b7675d
  trigger:
    platform: state
    entity_id: sensor.home_next_rain
    to: 'unknown'
  action:
    - service: notify.telegram
      data:
        message: "Plus de pluie attendue dans la prochaine heure."
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.stop_rain_notification

- alias: "Stop sending notification"
  trigger:
    platform: state
    entity_id: sensor.home_next_rain
  condition:
    # Check if rain is expected in less than 5 minutes
    - "{{ state_attr('sensor.home_next_rain', '1_hour_forecast')['O min'] != 'Temps sec' }}"
  action:
    # Protection to ensure other automations are triggered and conditions OK
    - delay: '00:01'
    # No more notification after having notify rain in following 5 minutes.
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.stop_rain_notification

- alias: "Send audio warning when rain is coming"
  trigger:
    platform: state
    entity_id: sensor.home_next_rain
  condition:
    - "{{ state_attr('sensor.home_next_rain', '1_hour_forecast')['0 min'] != 'Temps sec' }}"
    - condition: time
      before: '21:30:00'
      after: '10:00:00'
    - condition: state
      entity_id: input_boolean.stop_rain_notification
      state: 'off'
  action:
    - service: tts.google_translate_say
      entity_id: media_player.google_home
      data:
        message: "Chères résidents, la pluie est attendue dans quelques minutes."
