---
# E: Send Telegram notification when wheather alert is raised and when no more weather alert is active
# F: Envoie une notification Telegram quand une alerte météo est en cours et quand toutes les alertes sont terminées
#
# Exemple / Example:
# ------------------------------
# Alerte météo Orange en cours:
# - Orages: Jaune
# - Canicule: Orange
#
- id: bb9f2730-ee77-11ea-9220-4198f0db79cf
  alias: Notification pour alerte météo
  description: Envoie une notification sur Telegram en cas d'alerte météo.
  use_blueprint:
    path: my_blueprints/meteofrance_weather_alert.yaml
    input:
      sensor_weather_alert: sensor.home_weather_alert
      notifier: notify.telegram
