---
# Send a notification if a leak is detected
#
- alias: 'Send notification when water leak detected'
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.water_leak_sensor_buanderie
      to: 'on'
  action:
    - service: notify.telegram
      data:
        message: "ATTENTION! Fuite d'eau detectée {{trigger.to_state.attributes.friendly_name}}."
