---
# FR: Envoie une notification is une fuite est détectée
# EN: Send a notification if a leak is detected
#
- alias: "Alerte si fuite d'eau détectée"
  description: Envoie une notification sur Telegram si une fuite d'eau est détectée
  id: 0445ea10-3080-11eb-8655-7fbd7c468bda
  trigger:
    - platform: state
      entity_id: binary_sensor.water_leak_sensor_buanderie
      to: 'on'
  action:
    - service: notify.telegram
      data:
        message: "ATTENTION! Fuite d'eau detectée {{trigger.to_state.attributes.friendly_name}}."
