---
# FR: Mise à jour de l'historique des derniers mouvements
# EN: Update the history of last motion using the 'last_motion' variable
#
# https://github.com/rogro82/hass-variables/
#
- alias: "Mise à jour du dernier mouvement"
  description: "Met à jour l'historique des derniers mouvement détectés dans les attributs de last_motion."
  id: 57414134-042e-11eb-adc1-0242ac120002
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_livingroom, binary_sensor.presence_sous_sol
      to: 'on'
  action:
    - service: variable.set_variable
      data:
        variable: last_motion
        attributes:
          history_1: "{{states('variable.last_motion')}}"
          history_2: "{{state_attr('variable.last_motion','history_1')}}"
          history_3: "{{state_attr('variable.last_motion','history_2')}}"
        value: "{{ trigger.to_state.attributes.friendly_name }}"
