---
# E: Sensor with the estimated date of the end of charge for the Zoé
# F: Sensor avec la date estimée de la fin de charge de la Zoé
#
# https://github.com/epenet/hassRenaultZE
#
platform: template
sensors:
  zoe_end_of_charge_time:
    value_template: >-
      {{ (as_timestamp(state_attr('sensor.zoe_charging_remaining_time','last_update'))
      + states('sensor.zoe_charging_remaining_time') | int *60)
      | timestamp_custom('%Y-%m-%dT%H:%M:%S%z')}}
    availability_template: >-
      {{  states('sensor.zoe_charging_remaining_time') | int  > 0  }}

    friendly_name: "Date de fin de charge"
    icon_template: mdi:battery-charging-100
    device_class: timestamp
