---
# Computation of the theoretical mileage target for the Zoé
#
# To check consistency compared to battery and car leasing contract
#
platform: template
sensors:
  zoe_mileage_target:
    value_template: >-
      {{ (((as_timestamp(strptime(states('sensor.date'), '%Y-%m-%d')) - as_timestamp('2018-08-16 0:0:00+02:00'))
      / 86400) * 72500 / (365*4 +30)) | round}}
    friendly_name: "kilométrage cible"
    unit_of_measurement: "km"
    icon_template: mdi:bullseye-arrow
