---
name: Home Assistant configuration

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
      - main
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  yamllint:
    name: YAMLlint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Running YAMLlint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .

  link-checker:
    name: Link Checker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Link Checker
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.8
        with:
          use-quiet-mode: 'yes'

  remarklint:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          args: "remark --no-stdout --color --frail --use preset-lint-recommended ."

  home_assistant_stable:
    runs-on: ubuntu-latest
    needs: [yamllint, remarklint, link-checker]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* ./config
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --config ./config/ --script check_config  --info all
  home_assistant_beta:
    runs-on: ubuntu-latest
    needs: [yamllint, remarklint, link-checker]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* ./config
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: |
            python -m homeassistant --config ./config/ --script check_config  --info all
