---
# Launch my Xiaomi Vacuum in the living room, the kitchen, the entrance and utility room
#
# https://www.home-assistant.io/components/vacuum/
# https://www.home-assistant.io/components/vacuum.xiaomi_miio/
#
alias: Lance Rocky dans la cuisine et le salon et l'entrée
sequence:
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.rocky
      fan_speed: Standard
  - service: xiaomi_miio.vacuum_clean_zone
    data:
      entity_id: vacuum.rocky
      repeats: 1
      zone:
        - [20600, 25500, 30500, 29300]
        - [25500, 25500, 30600, 32600]
        - [23000, 29700, 25500, 34100]
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.vacuum_need_to_be_emptied
